config/routes.rb
Rails.application.routes.draw do

    devise_for :admins, controllers: {sessions:  "admins/sessions", registrations:  "admins/registrations"}
    devise_for :users, controllers: {sessions:  "users/sessions",registrations:  "users/registrations"}
   
    resources :posts do 
        resources :comments
    end
 
    root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

    has_many :comments, dependent: :destroy
    belongs_to :user
    validates_presence_of :tittle
    validates_presence_of :tittle, :message => "Tienes que poner titulo"
    validates_length_of :body,:in=> 10..400, :message => "Longuitud no valida"
    
    attr_accessor :photo
    FOTOS = File.join Rails.root, 'public', 'photo_store'
    after_save :guardar_foto
    
    def photo=(file_data)
        unless file_data.blank?
            @file_data = file_data
            self.extension = file_data.original_filename.split('.').last.downcase  
        end
    end
    
    def photo_filename 
        File.join FOTOS, "#{id}.#{extension}"
    end
    
    def photo_path
        "/photo_store/#{id}.#{extension}"
    end    
    
    def has_photo?
        File.exists? photo_filename
    end
    
    
    private
    def guardar_foto
        if @file_data 
            FileUtils.mkdir_p FOTOS
            File.open(photo_filename, 'wb') do |f| 
                f.write(@file_data.read)
            end
            @file_data = nil
            
        end        
    end

    has_many:comments
    validates_presence_of:title
    validates_presence_of:body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    #protect_from_forgery :except => [:index, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :auth_user!  
       
  def index      
     if admin_signed_in?
          @posts = Post.all
          respond_to do |format| 
              format.json do 
                  render :json => @posts, :callback => params[:callback] 
              end 
              format.html
         end
     end
      if user_signed_in? 
         @posts = current_user.posts
          respond_to do |format|
             format.json do 
                render :json => @posts, :callback => params[:callback] 
             end 
              format.html
          end
      end
        

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit

      if user_signed_in?
      if cannot? :update, @posts
          flash[:error]="No tiene permisos para editar"
          redirect_to :action => 'index'
      end
      end
      
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
         # Correo.bienvenida().deliver_now
          flash[:success]="Se guardo el post correctamente"
          format.html{ redirect_to @post}
          #format.html { redirect_to @post, notice: 'El post se ha creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @post }
        format.json do
            render :json => @post, :callback => params[:callback]
        end
      else
          flash[:alert]='Ocurrio un problema al crear el post'


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

      #Verificar si el usuario tiene permisos para editar
      
      
    respond_to do |format|
      if @post.update(post_params)
          flash[:success]="Se actualizo correctamente"
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
          flash[:alert]="No se actualizo :C"

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|

        flash[:info]= "El posts se borro correctamente"
        format.html{redirect_to posts_url}
      #format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }

      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }

      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params

        params.require(:post).permit(:tittle, :body, :categoria, :photo)
    end
end

      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
    <div class=" field small-10 columns">
            <%= f.label :titulo %><br>
        <%= f.text_field :tittle, :class => "validate[required]" %>
               
        <% categoria ={
    "Educación" => "Educación",
    "Deportes" => "Deportes",
    "Espectaculos" => "Espectaculos",
    "Alimentos" => "Alimentos",
    "Cultura" => "Cultura",
        }%>
        <%= f.label :categoria%> <br>
        <%= f.select :categoria, categoria, :class => "validate[required]"%>
        <%= f.label :contenido %><br>
        <%= f.text_area :body, :class => "validate[required]" %> 
        <!--Etiqueta de las fotos-->
        <%= f.label :foto %>
        <%= f.file_field :photo %>
    </div>
</div>

<div class="row">
    <div class="small-5 columns">
        <div class="actions">
            <%= f.submit 'Aceptar', :class => 'button small round' %>     
            <br/>
            <%= link_to 'Back', posts_path %>
        </div>
    </div>
</div>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
        <li class="name">
            <h1 class="titulo">BLOG</h1>
        </li>
    </ul>
    <section class="top-bar-section" id="barra">
        <ul class="left">
            <li class="has-dropdown not-click"><a href="#"> Opciones</a>
                <ul class="dropdown">
                    <li class="parent-link show-for-small-only">
                        <a class="parent-link js-generated" href="#"></a>
                    </li>
                    <li>
                        <label> Posts </label>
                    </li>
                    <li class="link">
                        <%= link_to 'Ver', controller: '/posts', action:'index'%>
                    </li>
                    <% if user_signed_in? %>
                    <li class="link">
                        <%= link_to 'Nuevo', controller: '/posts', action:'new'%>
                    </li>
                    <%end%>
                </ul>
            </li>
            
        </ul>
    <!-- Seccion Derecha -->
        
        
        <ul class="right">
	 	<% if user_signed_in? %>
            <li> <img src="/photo/<%= current_user.id%>.<%=current_user.extension_user%>" width="35px" height="35px" /></li>
	 	<li class="usuario"> Bienvenido(a) <strong> <%= current_user.email   %></strong></a></li>
    
    <li> <%= link_to 'Editarr Perfil', edit_user_registration_path , :class => 'navbar-link'%> </li>
    <li> <%= link_to "Cerrar Sesion ",destroy_user_session_path ,method: :delete,:class => 'navbar-link'%>
	 	</li>

	 	<% elsif admin_signed_in? %>
 <li> <img src="/photo/<%= current_admin.id%>.<%=current_admin.extension_user%>" width="35px" height="35px" /></li>
	 		<li class="usuario"> Bienvenido(a) <strong> <%= current_admin.email   %></strong></a></li>
<li> <%= link_to 'Editar Perfil', edit_admin_registration_path , :class => 'navbar-link'%> </li>
<li> <%= link_to "Cerrar Sesion ",destroy_admin_session_path ,method: :delete,:class => 'navbar-link'%>
	 	</li>
	 		

	 	<% else %>
	 	<li><%= link_to "Sing up",new_user_registration_path  ,:class=> 'navbar-link'%></li>
	 	<li><%= link_to "Login",new_user_session_path ,:class => 'navbar-link' %></li>
	 	<% end %>

	 </ul>
    </section>
</nav>

app/views/posts/edit.html.erb
<div class="row">
    <div class="small-5 columns">
        <h1>Editar Post</h1>
    </div>
</div>

<%= render 'form' %>


<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
    <div class="small-12 columns">
        <h1>Lista de Post</h1>
        <br/>
        <table>
  <thead>
    <tr>
      <th class="etiqueta1">Titulo</th>
      <th class="etiqueta1">Categoria</th>        
      <th class="etiqueta1">Contenido</th>
        <th class="etiqueta1">Imagen</th>
        <% if admin_signed_in?%>
      <th class="etiqueta1">Usuario</th>
        <%end%>
      <th class="etiqueta" colspan="3"> Opciones</th>

<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>

       
        <td class="contenido"><%= post.tittle %></td>
          <td class="contenido"><%= post.categoria%></td>
        <td class="contenido">
        	<% if post.body %>
        	<a href="#" data-reveal-id="body-<%=post.id%>">Ver</a>
        	<div id="body-<%=post.id%>" class="reveal-modal" data-reveal>
        	<%= post.body %>
        	<a class="close-reveal-modal">&#215;</a>
        	</div>

        	<% end %>
        </td>
          <td class="contenido">
              <img src="/photo_store/<%= post.id%>.<%=post.extension%>" width="30px" height="30px" />
          </td>
          <% if admin_signed_in?%>
          <td class="contenido"> 
            <div>          
              <%= User.find(post.user_id).email %>                
            </div>
          </td>
          <%end%>
          
          <td class="contenido"><%= link_to 'Comentar', post %></td>
        <td class="contenido"><%= link_to 'Editar', edit_post_path(post) %></td> 
        <td class="contenido"><%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         
          
          
          

        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

        <% if user_signed_in? %>
            <%= link_to 'New Post', new_post_path %>
        <% end %>
    </div>
</div>
<br>


<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="row">
    <div class="medium-8 columns">
        <h1>Nuevo Post</h1>
        
<%= render 'form' %>
    </div>
</div>


<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
    <div class="small-10 columns">
        <br>
        <p>
            <strong class="etiqueta">Titulo:</strong>
            <%= @post.tittle %>
        </p>
        <p >
            <strong class="etiqueta">Categoria:</strong>
            <%= @post.categoria %>
        </p>

        <p>
            <strong class="etiqueta">Contenido:</strong>
            <%= @post.body %>
        </p>
        <p>
            
            <strong class="etiqueta">Imagen:</strong>
            <div class="imagen">
                <%=image_tag @post.photo_path %>
            </div>
        </p>
        
    </div>
</div>
<div class="row">
    <div class="small-8 columns">
        
<div id="comments">
 <%= render :partial => @post.comments.reverse %>
</div>
<%= form_for([@post, Comment.new], remote:true) do |f|%>
<p>
    <%= f.label :body, "Nuevo Comentario"%>
    <br/>
    <%= f.text_area :body%>
</p>
<p>
    <%= f.submit "Agregar Comentario", :class => 'button small round'%>
</p>
<%end%>
        
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
    </div>
</div>


<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<div id="comments">
    <%= render :partial => @post.comments.reverse %>
</div>
<%= form_for([@post, Comment.new]remote: true) do|f| %>
<p>
    <%= f.label :body, "New Comment" %> <br/>    
    <%= f.text_area :body%> 
</p>
<p><%= f.submit "Add Comment"%></p>
<%end %>